### ISSUE TITLE
Manifest TypeError: Cannot read property 'importedCss' of undefined

### ISSUE THREAD

**Issue by heathsnee** [samrum/vite-plugin-web-extension#22]
I am getting an error when trying to build my extension:

```
rendering chunks (11)...[webExtension] Cannot read property 'importedCss' of undefined
error during build:
TypeError: Cannot read property 'importedCss' of undefined
    at ManifestV2.getMetadataforChunk (node_modules/@samrum/vite-plugin-web-extension/dist/index.js:335:32)
```

the same error happens for V3

```
rendering chunks (10)...[webExtension] Cannot read property 'importedCss' of undefined
error during build:
TypeError: Cannot read property 'importedCss' of undefined
    at ManifestV3.getMetadataforChunk (node_modules/@samrum/vite-plugin-web-extension/dist/index.js:335:32)
```

Also when trying to use it directly in vite plugins i get the error:

```
Type 'Plugin' is not assignable to type 'PluginOption | PluginOption[]'.
```

`"vite": "^2.8.6"`

so i had to move it to rollup options

```
export default defineConfig({
	plugins: [
		react(),
	],
	build: {
		rollupOptions: {
			plugins: [
				webExtension({ manifest }),
			],
		},
	},
})
```

**Comment by heathsnee** [comment]
thanks this helped!
